### ISSUE TITLE
Select version leads to "page not found" error

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_PublicationHelper#12]
![image](https://user-images.githubusercontent.com/15946467/87251268-91357a80-c46a-11ea-9290-784a59bee470.png)

![image](https://user-images.githubusercontent.com/15946467/87251281-b3c79380-c46a-11ea-8a82-5f985e6967b3.png)

**Comment by EleonoraPetzold** [comment]
fixed https://github.com/bexis/Module_PublicationHelper/commit/3878125d0b51010cf6ab80d6a2745880320cb4d1
