### ISSUE TITLE
Email pattern incomplete

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_PublicationHelper#13]
![image](https://user-images.githubusercontent.com/15946467/87251318-1325a380-c46b-11ea-9953-3a9285cafeb1.png)

- [x] check XSD
- [x] repair

**Comment by EleonoraPetzold** [comment]
https://github.com/bexis/BExIS-intern/commit/b00a67da8a41d4dcdf5d8e9cc58e4587e5fb9d4c#diff-044e89c75b31aea300e5df4782f6b1d8
