### ISSUE TITLE
Upload button lead to DCM upload

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_PublicationHelper#16]
![image](https://user-images.githubusercontent.com/15946467/90600086-3aa02680-e1f6-11ea-9940-5104e3a76a9c.png)

![image](https://user-images.githubusercontent.com/15946467/90600010-1e9c8500-e1f6-11ea-9dd7-7e46b03e595c.png)

**Comment by EleonoraPetzold** [comment]
This is hardcoded in MMM:
https://github.com/BEXIS2/Core/blob/2ca192b143e7ec63ec28f6fbc97473e8552eb3b2/Console/BExIS.Web.Shell/Areas/MMM/Views/ShowMultimediaData/_multimediaData.cshtml#L39

Not so easy to solve it. We can put here as an easy solution a link to our upload ...put such solutions are to so nice. Maybe we can speak to martin?

**Comment by geofranzi** [comment]
We can add a ‚if‘ only in our core. We will need still both options. Or add a variable with a default setting (as it is) and optional with something else on the main  Core.

**Comment by geofranzi** [comment]
Was soll denn eigentlich dort ausgefunden werden? Welcher Link? Wenn ich das nehme was beim Upload workflow genommen wird, wird keine Datei hochgeladen (...PUB/UploadPublication?entityId=4) . Außerdem wird beim Anlegen einer neuen Publikation zur DCm Anicht weitergeleitet. Das passt irgendwie auch nicht.

**Comment by geofranzi** [comment]
Änderungen in unserem Core
https://github.com/bexis/Core/commit/3fc434111032d00c83b205a1d37ac0eab636ac1e
https://github.com/bexis/Core/commit/9f5bfddf571b3f2331933d8f7c6bc6d41e068633

**Comment by EleonoraPetzold** [comment]
> Wenn ich das nehme was beim Upload workflow genommen wird, wird keine Datei hochgeladen (...PUB/UploadPublication?entityId=4)

Das Problem war wieder der name des ContentDescriptors. der war auf den filename gesetzt und nicht auf "unstructureddata".
