### ISSUE TITLE
Upload file on existing Metadata leads to DCM show page

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_PublicationHelper#19]
![image](https://user-images.githubusercontent.com/15946467/95779374-378f5700-0cca-11eb-83b6-956c92e18b21.png)

**Comment by geofranzi** [comment]
Hm, nur beim Ersten mal passiert ...dann nicht wieder. Da war auch vorher dann der Upload Link verkehrt.

**Comment by EleonoraPetzold** [comment]
The problem is fixed
