### ISSUE TITLE
Add js to metadata structure

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_PublicationHelper#2]
ext.js:

function init_state(){
    jQuery("#upload").hide();
 }

jQuery(document).ready(function(){

    init_state();
});

**Comment by EleonoraPetzold** [comment]
what do you mean here? why do we need this? @geofranzi

**Comment by geofranzi** [comment]
To hide the uploade button via js.. but I think we removed hardcoded niw, or?

**Comment by EleonoraPetzold** [comment]
i don't know which upload is meant but upload file works as it should and there is no other. Issue can be closed
