### ISSUE TITLE
Upload file error, if directory not exists

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_PublicationHelper#20]
![image](https://user-images.githubusercontent.com/15946467/95781870-f64d7600-0cce-11eb-8238-08e5408b77a2.png)

```C#
                //check if directory exist
                // if folder not exist
                var directory = Path.GetDirectoryName(storePath);
                if (!Directory.Exists(directory)) Directory.CreateDirectory(directory);
```
(copy from DataAsyncUploadHelper)

**Comment by geofranzi** [comment]
beim einem Fehler wird die neue Version angelegt. Weiß nicht genau wo das passiert und ob man das beeinflussen kann, wenn aus der Move Funktion ein Fehler kommt. Ich leg auch mal ein Core ticket zu der Funktion an. (https://github.com/BEXIS2/Core/issues/656)

**Comment by EleonoraPetzold** [comment]
solved with https://github.com/bexis/Module_PublicationHelper/commit/9d882f3eb38bdaedd9751ee7facf28c3fbc4b86a
