### ISSUE TITLE
Delete for files missing

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_PublicationHelper#21]
I do not know why ....in general and in PUB
![image](https://user-images.githubusercontent.com/15946467/95783229-b76cef80-0cd1-11eb-957c-6886ceb8b16b.png)

**Comment by EleonoraPetzold** [comment]
geht jetzt:
![image](https://user-images.githubusercontent.com/42029171/100199020-e5fafe80-2efc-11eb-9145-23f61947bb2a.png)
