### ISSUE TITLE
public publications are not visible in the public search

### ISSUE THREAD

**Issue by DavidBlaa** [bexis/Module_PublicationHelper#24]
datasets and other entities can be set to public under entity permissions.
after that they must be visible in the public search. unfortunately they are currently not to be found there.

**Comment by EleonoraPetzold** [comment]
Maybe only for dataset entity, too. We should check this in the core.

**Comment by aostrow** [comment]
as a first step: check if it is easy to implement

**Comment by EleonoraPetzold** [comment]
With version 3 and entiytemplates no extra publication module needed and this problem doesn't matter.
