### ISSUE TITLE
download metadata as xml and html doesn't work

### ISSUE THREAD

**Issue by CFuerstenau** [bexis/Module_PublicationHelper#29]
![grafik](https://user-images.githubusercontent.com/45873895/101761597-a592a780-3adc-11eb-977b-1f80d55630df.png)

**Comment by EleonoraPetzold** [comment]
Works with html

**Comment by EleonoraPetzold** [comment]
Is a problem of our Pub metadata. DocumentElement is missing:
![image](https://user-images.githubusercontent.com/42029171/131806954-cbc360ed-c34c-42be-8b38-bb062c7911a5.png)

In opposition to dataset schema:
![image](https://user-images.githubusercontent.com/42029171/131806454-8fc361e5-34b7-48f5-949d-f6775556464e.png)

**Comment by EleonoraPetzold** [comment]
Source and destination in mapping file were interchanged. Thereby the xml download did not work anymore.
Commit in workspace: https://github.com/bexis/Workspace/commit/8d194f0ff0ef597652094a0d1dce5384f6049b20
