### ISSUE TITLE
Remove or Adjust "Copy"

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_PublicationHelper#33]
![image](https://user-images.githubusercontent.com/15946467/107858681-9d851a00-6e35-11eb-8cd1-2692da4f4a44.png)

![image](https://user-images.githubusercontent.com/15946467/107858691-aece2680-6e35-11eb-8f30-0123c89b9350.png)

**Comment by EleonoraPetzold** [comment]
Das "Problem" liegt hier:
https://github.com/bexis/Core/blob/30cd97e4862608e9ab3b842dc26c7095494560f3/Console/BExIS.Web.Shell/Areas/DCM/Controllers/CreateDatasetController.cs#L835
dadurch das dort nur datasets geladen werden funktioniert copy nicht.
Den Copy button einfach rausnehmen geht auch nicht da wri den Core view verwenden.
Man könnte an der Stelle den type (Dataset|Publication) ,mit default = dataset übergeben. So haben wir es schon an anderen Stellen gemacht. @geofranzi , was sagst du?

**Comment by geofranzi** [comment]
Copy ist glaube auch ein neuer Parameter im TaskManger ...d.h. wir können glaube mitgeben das wird es nicht wollen. Brauchen wir "Copy"?

Unabhängig davon: Ja das hard coded "Dataset" wäre gut auszubauen.

**Comment by geofranzi** [comment]
Ist ein Parameter. 
![image](https://user-images.githubusercontent.com/15946467/109127221-7809e180-774e-11eb-9658-ecba83251403.png)

**Comment by EleonoraPetzold** [comment]
Die action war aus kommentiert und wir haben sie nicht mitgegeben aber nur weil es keine action gibt wird der button nicht ausgeblendet. eigentlich brauchen wir bei den Pubs kein Copy...

**Comment by EleonoraPetzold** [comment]
vlt kann man ja einbauen das der button ausgeblendet wird ... wäre noch schöner für uns an der stelle

**Comment by geofranzi** [comment]
Default ist "true". aktiv auf "false" sollte eigentlich helfen.

**Comment by EleonoraPetzold** [comment]
Zumal wenn man dann bei Copy ist in der Submit wieder das prob mit dataset besteht:
https://github.com/bexis/Core/blob/30cd97e4862608e9ab3b842dc26c7095494560f3/Console/BExIS.Web.Shell/Areas/DCM/Controllers/CreateDatasetController.cs#L513
 ... hab es gerade mal gestetet und temp "Publication" bei der Liste übergeben.

**Comment by EleonoraPetzold** [comment]
> Default ist "true". aktiv auf "false" sollte eigentlich helfen.

mom ich schau mal wo das gesetzt wird...
