### ISSUE TITLE
Bug publication schema - save

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_PublicationHelper#35]
Case: the metadata of a publication is not fully filled
When I click save I see the error message for all unfilled fields
![grafik](https://user-images.githubusercontent.com/45873895/105724055-bdf14100-5f27-11eb-87ef-3f893cb06c8e.png)
When I click save the second time, I get the message which already should be there at the first time
![grafik](https://user-images.githubusercontent.com/45873895/105724138-d3ff0180-5f27-11eb-99aa-f098c8f2b9c0.png)

**Comment by geofranzi** [comment]
maybe core issue ...not sure. Can be related to "save without error"

**Comment by CFuerstenau** [comment]
Könnt Ihr bitte noch mal schauen, ob das ein Core issue ist!
Bevor ich das How to fertigstelle, würde ich gern wissen, welche Version ich rein schreibe (2 x save oder 1 x save)

**Comment by EleonoraPetzold** [comment]
@geofranzi hast du das auf dem Schirm?
