### ISSUE TITLE
Bug publication schema - validate -> no  cancel button

### ISSUE THREAD

**Issue by CFuerstenau** [bexis/Module_PublicationHelper#36]
Case: I open an already exsiting publication. Do changes. Validate. Get an error message (The metadata you entered is either not complete...). Therefore I don't want to save my changes.
Problem: Don't have a cancel button

Same applies in combination of save and error message 
![grafik](https://user-images.githubusercontent.com/45873895/108473016-c40be080-728d-11eb-8b37-28da72aee07e.png)

**Comment by EleonoraPetzold** [comment]
This issue came from core. when you edit a datasets and validate there is not cancel button, too. 
Bug or feature?

**Comment by geofranzi** [comment]
https://github.com/BEXIS2/Core/issues/711
