### ISSUE TITLE
Field Type of publications - german article is missing in list

### ISSUE THREAD

**Issue by CFuerstenau** [bexis/Module_PublicationHelper#38]
Im Feld Type of publication gibt es german article nicht in der Liste und es gibt eine Fehlermeldung, wenn solche Datensätze bearbeitet werden.

Beispiel: 30834

**Comment by EleonoraPetzold** [comment]
`select * from datacontainers where name like 'typeOfPublicationType'`

`select * from constraints where datacontainerref = `
--> update xmldomainitems:
`<Item Name="DomainItem" typeid="1"><Property Name="Key" typeid="2" value="German article" /><Property Name="Value" typeid="2" value="German article" /></Item>`
