### ISSUE TITLE
Rename " german article" in "German article"

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_PublicationHelper#39]

**Comment by EleonoraPetzold** [comment]
https://github.com/BEXIS2/Core/wiki/How-to-update-Metadata-without-new-version-(in-DB)

**Comment by geofranzi** [comment]
`update datasetversions set metadata = Replace(metadata::text, '>german article<', '>German article<')::xml where metadata::text ilike '%german article%'`
