### ISSUE TITLE
Double unstructured file type for publication

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_PublicationHelper#41]
I checked the database and it seems that:
- all migrated publications use the data structure with name "publication"
- all new created publications use data structure with name "publication-file"

We should use just one of it. 
Is the later data structure (publication-file) hardcoded? 

---
- [x] go for "Publication"
- [x] change Publication-File to Publication
- [x] remove Publication-FIle from system

**Comment by geofranzi** [comment]
Is the later data structure (publication-file) hardcoded? - Yes

https://github.com/bexis/Module_PublicationHelper/blob/941b958a7e37ea604aa32c6d73897d8b9834deb3/BEXIS.Modules.PUB.UI/Controllers/CreatePublicationController.cs#L100
