### ISSUE TITLE
Metadata field citation - has to be mandatory

### ISSUE THREAD

**Issue by CFuerstenau** [bexis/Module_PublicationHelper#50]
Das Metadatenfeld Citation muss mandatory sein, da die Zitation auf der BE Website eingefügt wird.
Im Hilfetext sollte ein Formatvorschlag sein.

**Comment by EleonoraPetzold** [comment]
schema changes. https://github.com/bexis/BExIS-intern/commit/f8c9a75f19ae80840a30d2b269622e26f0bd8ce4

**Comment by EleonoraPetzold** [comment]
@geofranzi ich weiß gar nicht wie ich das schema dann im system aktualisiere. Können wir das zusammen machen?

**Comment by EleonoraPetzold** [comment]
Franzi made the changes in the database:
mincardinality 0=>1
![image](https://user-images.githubusercontent.com/42029171/131824127-667492cf-df02-4381-93dc-49d85990d94e.png)
