### ISSUE TITLE
Download the publication together with metadata 

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_PublicationHelper#52]
Currently "just" the file is downloadable. We should provide the whole package (metadata + file(s)).

Think if this should be the only option?

**Comment by EleonoraPetzold** [comment]
BEXIS does not allow the download of metadata and files for unstructured datasets. The question is whether this is also intended.
For the publications, we use core functions for the download.

**Comment by EleonoraPetzold** [comment]
done and published
