### ISSUE TITLE
Publication Creations: automatically read rights to role

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_PublicationHelper#8]
after publication creation, the role publicationIntern need automatically read right on the it.

**Comment by geofranzi** [comment]
still open?

`entityPermissionManager.Create<Group>("administrator", "Dataset", typeof(Dataset), ds.Id, Enum.GetValues(typeof(RightType)).Cast<RightType>().ToList());` see https://github.com/bexis/Core/commit/dc65d2f4f328282c2bdc23ee8b9841f39ccaab3e

**Comment by EleonoraPetzold** [comment]
> still open?

for admin is still there but we need read rights for publicationIntern group. All people who are in that group have default read rights in B1. As I have described in issue desc.

**Comment by EleonoraPetzold** [comment]
for admin group we need to set by the PUB module, too. Because of the entity type.
